### ISSUE TITLE
Error displaying in echo-area + sideline

### ISSUE THREAD

**Issue by gchape** [emacs-sideline/sideline-flymake#11]
Can we enable to only display error messages with `sideline-flymake`? 

As you see, errors are also appended in `echo-area` in tandem with the `sideline` position.

![imageedit_0_6609021960](https://github.com/emacs-sideline/sideline-flymake/assets/118893979/d1e5fbe4-bddf-406e-9c31-c8751a2308da)

**Comment by jcs090218** [comment]
`sideline` doesn't echo anything by default, and I'm not able to reproduce this. 🤔 I know flycheck does echo messages by default, so make sure you only have flymake on and not flycheck.

**Comment by gchape** [comment]
> `sideline` doesn't echo anything by default, and I'm not able to reproduce this. 🤔 I know flycheck does echo messages by default, so make sure you only have flymake on and not flycheck.

It is **Flymake** that bounds `eldoc-documentation-functions` to errors and etc. 
After looking in, I found solution:
`(setq eldoc-documentation-functions
                  (remove #'flymake-eldoc-function eldoc-documentation-functions))
            `

You may consider disabling it along with sideline, because having both does not make sense.
