### ISSUE TITLE
Option to get errors from the whole line

### ISSUE THREAD

**Issue by heyitscassio** [emacs-sideline/sideline-flymake#3]
By default, lsp-ui shows errors for the whole line, and now that i'm using flymake, I wanted to keep that behaviour. So I had to do this:

```elisp
(defun my-sideline-flymake--get-errors ()
  (flymake-diagnostics (line-beginning-position) (line-end-position)))

(advice-add 'sideline-flymake--get-errors :override #'my-sideline-flymake--get-errors)
```

The result is this:
![image](https://user-images.githubusercontent.com/14265358/202864063-658a5985-7d8d-4453-87cb-0e9226ef1310.png)

 It's kinda hacky, and it would be nice if there was a variable that you could toggle that funcionality.
 
 Is this something that you are interested? I could make a PR making that possible, letting the default be the current behaviour.

**Comment by jcs090218** [comment]
Yes, I was thinking about this feature! Feel free to create a PR for this! ❤️ 👍
