### ISSUE TITLE
Error running timer ‘sideline-render’: (void-function sideline-flymake)

### ISSUE THREAD

**Issue by philipmw** [emacs-sideline/sideline-flymake#8]
I just installed `sideline-20240222.151` into Emacs 29.2 on macOS. When I open a file that triggers it (a Clojure file in this case), I get this in `*Messages*`:

> Error running timer ‘sideline-render’: (void-function sideline-flymake)

The error repeats for each such file I open.

As an Emacs newbie, I don't know how to debug this further.

**Comment by jcs090218** [comment]
Did you install this package `sideline-flymake`? 🤔 Make sure the module is loaded by adding `(require 'sideline-flymake)` to your `init.el` file.

**Comment by philipmw** [comment]
I am following the instructions in your README:
https://github.com/emacs-sideline/sideline-flymake?tab=readme-ov-file#-quickstart

Do we need to replace `(use-package sideline` with `(use-package sideline-flymake`?

**Comment by philipmw** [comment]
Yep, making that change solved the problem. So now the only problem is that the README has wrong instructions. Can you make the change or do you want me to submit a PR?

**Comment by jcs090218** [comment]
I'm glad you have resolved it! And, sorry for the misleading documentation. I assumed people would know they need both packages installed, but that's not true. 😓 

> Can you make the change or do you want me to submit a PR?

Yes, feel free to open PR(s) for this.
